name: Pull Request Checks
on:
  pull_request: 
    branches:
      - main
  workflow_dispatch: 
jobs: 
    pull-request-checks:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Validate C# Class Creation
            run: |
              xsd
              xsd /c /n:DarwinPushPortSchema /o:DarwinPushPortSchema.cs v24/schemas/rttiPPTSchema_v18.xsd