name: Pull Request Checks
on:
  pull_request: 
    branches:
      - main
  workflow_dispatch: 
jobs: 
    pull-request-checks:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            # https://github.com/actions/checkout
            uses: actions/checkout@v4
          - name: Validate C# Class Creation
            run: |
              
              cd "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\"
              
              .\xsd "${{ github.workspce }}\v24\schemas\rttiPPTSchema_v18.xsd /c /out:${{ github.workspace }}\v24
              
              cd "${{ github.workspace }}\v24\"
              
              dir